# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    networks:
      - database
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - database
    ports:
      - 8080:8080

networks:
  database:
    driver: bridge
